"""Remove unidad_compra_predeterminada from productos

Revision ID: 04e10db77258
Revises: add_audit_logs_table
Create Date: 2025-09-26 14:25:17.091077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04e10db77258'
down_revision: Union[str, None] = 'add_audit_logs_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_accion', table_name='audit_logs')
    op.drop_index('idx_audit_logs_fecha', table_name='audit_logs')
    op.drop_index('idx_audit_logs_log_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_tabla', table_name='audit_logs')
    op.drop_index('idx_categorias_estado', table_name='categorias')
    op.drop_column('categorias', 'creado_en')
    op.alter_column('compras', 'fecha_compra',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('compras', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pendiente', 'completada', 'anulada', name='estadocompraenum'),
               nullable=False,
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.drop_index('idx_compras_estado', table_name='compras')
    op.drop_index('idx_compras_proveedor', table_name='compras')
    op.create_index(op.f('ix_compras_compra_id'), 'compras', ['compra_id'], unique=False)
    op.alter_column('conversiones', 'nombre_presentacion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint('uq_producto_presentacion', 'conversiones', type_='unique')
    op.create_index(op.f('ix_conversiones_id'), 'conversiones', ['id'], unique=False)
    op.alter_column('detalle_compras', 'compra_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detalle_compras', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detalle_compras', 'cantidad',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('detalle_compras', 'precio_unitario',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index('idx_detalle_compras_compra', table_name='detalle_compras')
    op.drop_index('idx_detalle_compras_producto', table_name='detalle_compras')
    op.create_index(op.f('ix_detalle_compras_detalle_id'), 'detalle_compras', ['detalle_id'], unique=False)
    op.drop_index('idx_detalle_ventas_producto', table_name='detalle_ventas')
    op.drop_index('idx_detalle_ventas_venta', table_name='detalle_ventas')
    op.create_index(op.f('ix_detalle_ventas_detalle_id'), 'detalle_ventas', ['detalle_id'], unique=False)
    op.drop_constraint('detalle_ventas_venta_id_fkey', 'detalle_ventas', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_ventas', 'ventas', ['venta_id'], ['venta_id'])
    op.drop_index('idx_empresas_estado', table_name='empresas')
    op.drop_index('idx_empresas_identificacion', table_name='empresas')
    op.create_index(op.f('ix_facturas_electronicas_factura_id'), 'facturas_electronicas', ['factura_id'], unique=False)
    op.alter_column('marcas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               nullable=False,
               existing_server_default=sa.text("'activo'::character varying"))
    op.create_index(op.f('ix_marcas_marca_id'), 'marcas', ['marca_id'], unique=False)
    op.create_index(op.f('ix_menus_menu_id'), 'menus', ['menu_id'], unique=False)
    op.alter_column('metodos_pago', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index('idx_metodos_pago_estado', table_name='metodos_pago')
    op.create_index(op.f('ix_metodos_pago_metodo_pago_id'), 'metodos_pago', ['metodo_pago_id'], unique=False)
    op.alter_column('movimientos_inventario', 'stock_anterior',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('movimientos_inventario', 'stock_nuevo',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
    op.drop_index('idx_movimientos_producto', table_name='movimientos_inventario')
    op.drop_index('idx_movimientos_tipo', table_name='movimientos_inventario')
    op.drop_index('idx_movimientos_usuario', table_name='movimientos_inventario')
    op.create_index(op.f('ix_movimientos_inventario_movimiento_id'), 'movimientos_inventario', ['movimiento_id'], unique=False)
    op.alter_column('personas', 'genero',
               existing_type=sa.CHAR(length=1),
               type_=sa.Enum('M', 'F', name='generoenum'),
               existing_nullable=True)
    op.alter_column('personas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index('idx_personas_ci', table_name='personas')
    op.drop_index('idx_personas_estado', table_name='personas')
    op.create_index(op.f('ix_personas_persona_id'), 'personas', ['persona_id'], unique=False)
    op.alter_column('productos', 'stock',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('productos', 'tipo_margen',
               existing_type=postgresql.ENUM('porcentaje', 'fijo', name='tipomargen'),
               type_=sa.Enum('porcentaje', 'fijo', name='tipomargenenum'),
               existing_nullable=False,
               existing_server_default=sa.text("'porcentaje'::tipomargen"))
    op.alter_column('productos', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               nullable=False,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index('idx_productos_categoria', table_name='productos')
    op.drop_index('idx_productos_codigo', table_name='productos')
    op.drop_index('idx_productos_estado', table_name='productos')
    op.create_index(op.f('ix_productos_producto_id'), 'productos', ['producto_id'], unique=False)
    op.drop_column('productos', 'unidad_compra_predeterminada')
    op.drop_index('idx_proveedores_empresa', table_name='proveedores')
    op.drop_index('idx_proveedores_estado', table_name='proveedores')
    op.drop_index('idx_proveedores_persona', table_name='proveedores')
    op.drop_constraint('rol_menus_menu_id_fkey', 'rol_menus', type_='foreignkey')
    op.drop_constraint('rol_menus_rol_id_fkey', 'rol_menus', type_='foreignkey')
    op.create_foreign_key(None, 'rol_menus', 'roles', ['rol_id'], ['rol_id'])
    op.create_foreign_key(None, 'rol_menus', 'menus', ['menu_id'], ['menu_id'])
    op.alter_column('roles', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index('idx_roles_estado', table_name='roles')
    op.create_index(op.f('ix_roles_rol_id'), 'roles', ['rol_id'], unique=False)
    op.create_index(op.f('ix_unidades_medida_unidad_id'), 'unidades_medida', ['unidad_id'], unique=False)
    op.alter_column('usuarios', 'estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index('idx_usuarios_nombre', table_name='usuarios')
    op.drop_index('idx_usuarios_persona', table_name='usuarios')
    op.drop_constraint('usuarios_nombre_usuario_key', 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.create_index(op.f('ix_usuarios_usuario_id'), 'usuarios', ['usuario_id'], unique=False)
    op.alter_column('ventas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'activa'::character varying"))
    op.drop_index('idx_ventas_estado', table_name='ventas')
    op.drop_index('idx_ventas_fecha', table_name='ventas')
    op.drop_index('idx_ventas_metodopago', table_name='ventas')
    op.create_index(op.f('ix_ventas_venta_id'), 'ventas', ['venta_id'], unique=False)
    op.drop_constraint('ventas_modificado_por_fkey', 'ventas', type_='foreignkey')
    op.drop_constraint('ventas_creado_por_fkey', 'ventas', type_='foreignkey')
    op.create_foreign_key(None, 'ventas', 'usuarios', ['creado_por'], ['usuario_id'])
    op.create_foreign_key(None, 'ventas', 'usuarios', ['modificado_por'], ['usuario_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.create_foreign_key('ventas_creado_por_fkey', 'ventas', 'usuarios', ['creado_por'], ['usuario_id'], ondelete='SET NULL')
    op.create_foreign_key('ventas_modificado_por_fkey', 'ventas', 'usuarios', ['modificado_por'], ['usuario_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_ventas_venta_id'), table_name='ventas')
    op.create_index('idx_ventas_metodopago', 'ventas', ['metodo_pago_id'], unique=False)
    op.create_index('idx_ventas_fecha', 'ventas', ['fecha_venta'], unique=False)
    op.create_index('idx_ventas_estado', 'ventas', ['estado'], unique=False)
    op.alter_column('ventas', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'activa'::character varying"))
    op.drop_index(op.f('ix_usuarios_usuario_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.create_unique_constraint('usuarios_nombre_usuario_key', 'usuarios', ['nombre_usuario'])
    op.create_index('idx_usuarios_persona', 'usuarios', ['persona_id'], unique=False)
    op.create_index('idx_usuarios_nombre', 'usuarios', ['nombre_usuario'], unique=False)
    op.alter_column('usuarios', 'estado',
               existing_type=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index(op.f('ix_unidades_medida_unidad_id'), table_name='unidades_medida')
    op.drop_index(op.f('ix_roles_rol_id'), table_name='roles')
    op.create_index('idx_roles_estado', 'roles', ['estado'], unique=False)
    op.alter_column('roles', 'estado',
               existing_type=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_constraint(None, 'rol_menus', type_='foreignkey')
    op.drop_constraint(None, 'rol_menus', type_='foreignkey')
    op.create_foreign_key('rol_menus_rol_id_fkey', 'rol_menus', 'roles', ['rol_id'], ['rol_id'], ondelete='CASCADE')
    op.create_foreign_key('rol_menus_menu_id_fkey', 'rol_menus', 'menus', ['menu_id'], ['menu_id'], ondelete='CASCADE')
    op.create_index('idx_proveedores_persona', 'proveedores', ['persona_id'], unique=False)
    op.create_index('idx_proveedores_estado', 'proveedores', ['estado'], unique=False)
    op.create_index('idx_proveedores_empresa', 'proveedores', ['empresa_id'], unique=False)
    op.add_column('productos', sa.Column('unidad_compra_predeterminada', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_productos_producto_id'), table_name='productos')
    op.create_index('idx_productos_estado', 'productos', ['estado'], unique=False)
    op.create_index('idx_productos_codigo', 'productos', ['codigo'], unique=False)
    op.create_index('idx_productos_categoria', 'productos', ['categoria_id'], unique=False)
    op.alter_column('productos', 'estado',
               existing_type=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'activo'::character varying"))
    op.alter_column('productos', 'tipo_margen',
               existing_type=sa.Enum('porcentaje', 'fijo', name='tipomargenenum'),
               type_=postgresql.ENUM('porcentaje', 'fijo', name='tipomargen'),
               existing_nullable=False,
               existing_server_default=sa.text("'porcentaje'::tipomargen"))
    op.alter_column('productos', 'stock',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_personas_persona_id'), table_name='personas')
    op.create_index('idx_personas_estado', 'personas', ['estado'], unique=False)
    op.create_index('idx_personas_ci', 'personas', ['ci'], unique=False)
    op.alter_column('personas', 'estado',
               existing_type=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'activo'::character varying"))
    op.alter_column('personas', 'genero',
               existing_type=sa.Enum('M', 'F', name='generoenum'),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.drop_index(op.f('ix_movimientos_inventario_movimiento_id'), table_name='movimientos_inventario')
    op.create_index('idx_movimientos_usuario', 'movimientos_inventario', ['usuario_id'], unique=False)
    op.create_index('idx_movimientos_tipo', 'movimientos_inventario', ['tipo_movimiento'], unique=False)
    op.create_index('idx_movimientos_producto', 'movimientos_inventario', ['producto_id'], unique=False)
    op.alter_column('movimientos_inventario', 'stock_nuevo',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('movimientos_inventario', 'stock_anterior',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_metodos_pago_metodo_pago_id'), table_name='metodos_pago')
    op.create_index('idx_metodos_pago_estado', 'metodos_pago', ['estado'], unique=False)
    op.alter_column('metodos_pago', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index(op.f('ix_menus_menu_id'), table_name='menus')
    op.drop_index(op.f('ix_marcas_marca_id'), table_name='marcas')
    op.alter_column('marcas', 'estado',
               existing_type=sa.Enum('activo', 'inactivo', 'bloqueado', name='estadoenum'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'activo'::character varying"))
    op.drop_index(op.f('ix_facturas_electronicas_factura_id'), table_name='facturas_electronicas')
    op.create_index('idx_empresas_identificacion', 'empresas', ['identificacion'], unique=False)
    op.create_index('idx_empresas_estado', 'empresas', ['estado'], unique=False)
    op.drop_constraint(None, 'detalle_ventas', type_='foreignkey')
    op.create_foreign_key('detalle_ventas_venta_id_fkey', 'detalle_ventas', 'ventas', ['venta_id'], ['venta_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_detalle_ventas_detalle_id'), table_name='detalle_ventas')
    op.create_index('idx_detalle_ventas_venta', 'detalle_ventas', ['venta_id'], unique=False)
    op.create_index('idx_detalle_ventas_producto', 'detalle_ventas', ['producto_id'], unique=False)
    op.drop_index(op.f('ix_detalle_compras_detalle_id'), table_name='detalle_compras')
    op.create_index('idx_detalle_compras_producto', 'detalle_compras', ['producto_id'], unique=False)
    op.create_index('idx_detalle_compras_compra', 'detalle_compras', ['compra_id'], unique=False)
    op.alter_column('detalle_compras', 'precio_unitario',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('detalle_compras', 'cantidad',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False)
    op.alter_column('detalle_compras', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('detalle_compras', 'compra_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_conversiones_id'), table_name='conversiones')
    op.create_unique_constraint('uq_producto_presentacion', 'conversiones', ['producto_id', 'nombre_presentacion'])
    op.alter_column('conversiones', 'nombre_presentacion',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_compras_compra_id'), table_name='compras')
    op.create_index('idx_compras_proveedor', 'compras', ['proveedor_id'], unique=False)
    op.create_index('idx_compras_estado', 'compras', ['estado'], unique=False)
    op.alter_column('compras', 'estado',
               existing_type=sa.Enum('pendiente', 'completada', 'anulada', name='estadocompraenum'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pendiente'::character varying"))
    op.alter_column('compras', 'fecha_compra',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('categorias', sa.Column('creado_en', postgresql.TIMESTAMP(), server_default=sa.text("'2025-05-12 14:02:20.06645'::timestamp without time zone"), autoincrement=False, nullable=True))
    op.create_index('idx_categorias_estado', 'categorias', ['estado'], unique=False)
    op.create_index('idx_audit_logs_tabla', 'audit_logs', ['tabla'], unique=False)
    op.create_index('idx_audit_logs_log_id', 'audit_logs', ['log_id'], unique=False)
    op.create_index('idx_audit_logs_fecha', 'audit_logs', ['fecha'], unique=False)
    op.create_index('idx_audit_logs_accion', 'audit_logs', ['accion'], unique=False)
    # ### end Alembic commands ###
