"""Add audit_logs table

Revision ID: add_audit_logs_table
Revises: f9e8a7b6c1d2
Create Date: 2025-09-17 23:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_audit_logs_table'
down_revision = 'f9e8a7b6c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=10), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('valores_antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valores_despues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_accion'), 'audit_logs', ['accion'], unique=False)
    op.create_index(op.f('ix_audit_logs_fecha'), 'audit_logs', ['fecha'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tabla'), 'audit_logs', ['tabla'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_tabla'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_fecha'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_accion'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###